/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DbgRouteImport } from './routes/dbg'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PainelGruposRouteImport } from './routes/painel.grupos'
import { Route as PainelInstagramRouteImport } from './routes/painel.instagram'
import { Route as PainelOportunidadesRouteImport } from './routes/painel.oportunidades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DbgRoute = DbgRouteImport.update({
  id: '/dbg',
  path: '/dbg',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelGruposRoute = PainelGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelInstagramRoute = PainelInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => PainelRoute,
} as any)
const PainelOportunidadesRoute = PainelOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dbg': typeof DbgRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/grupos': typeof PainelGruposRoute
  '/painel/instagram': typeof PainelInstagramRoute
  '/painel/oportunidades': typeof PainelOportunidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dbg': typeof DbgRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/grupos': typeof PainelGruposRoute
  '/painel/instagram': typeof PainelInstagramRoute
  '/painel/oportunidades': typeof PainelOportunidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dbg': typeof DbgRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/grupos': typeof PainelGruposRoute
  '/painel/instagram': typeof PainelInstagramRoute
  '/painel/oportunidades': typeof PainelOportunidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dbg'
    | '/painel'
    | '/painel/grupos'
    | '/painel/instagram'
    | '/painel/oportunidades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dbg'
    | '/painel'
    | '/painel/grupos'
    | '/painel/instagram'
    | '/painel/oportunidades'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dbg'
    | '/painel'
    | '/painel/grupos'
    | '/painel/instagram'
    | '/painel/oportunidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DbgRoute: typeof DbgRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dbg': {
      id: '/dbg'
      path: '/dbg'
      fullPath: '/dbg'
      preLoaderRoute: typeof DbgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/grupos': {
      id: '/painel/grupos'
      path: '/grupos'
      fullPath: '/painel/grupos'
      preLoaderRoute: typeof PainelGruposRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/instagram': {
      id: '/painel/instagram'
      path: '/instagram'
      fullPath: '/painel/instagram'
      preLoaderRoute: typeof PainelInstagramRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/oportunidades': {
      id: '/painel/oportunidades'
      path: '/oportunidades'
      fullPath: '/painel/oportunidades'
      preLoaderRoute: typeof PainelOportunidadesRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelGruposRoute: typeof PainelGruposRoute
  PainelInstagramRoute: typeof PainelInstagramRoute
  PainelOportunidadesRoute: typeof PainelOportunidadesRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelGruposRoute: PainelGruposRoute,
  PainelInstagramRoute: PainelInstagramRoute,
  PainelOportunidadesRoute: PainelOportunidadesRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DbgRoute: DbgRoute,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
